import mysql.connector
from mysql.connector import errorcode

try:
    config = {
        'user': 'root',
        'password': '123456',
        'host': 'localhost',
        'database': 'yoyo-bot',
        'raise_on_warnings': True
        }

    cnx = mysql.connector.connect(**config)
    print("database connected")
    mycursor = cnx.cursor()
    mycursor.execute("SELECT * FROM Customerdetails")
    myresult = mycursor.fetchall()
    for x in myresult:
      print(x)
    cnx.close()
except mysql.connector.Error as err:
  if err.errno == errorcode.ER_ACCESS_DENIED_ERROR:
    print("Something is wrong with your user name or password")
  elif err.errno == errorcode.ER_BAD_DB_ERROR:
    print("Database does not exist")
  else:
    print(err)
else:
  cnx.close()
